language: java
jdk:
  - oraclejdk8
install: ./configure-mvn.sh
after_success:
  - test "${TRAVIS_BRANCH}" == "master" && mvn clean
  - test "${TRAVIS_BRANCH}" == "master" && mvn release:prepare
  - test "${TRAVIS_BRANCH}" == "master" && mvn release:perform
