language: java
jdk:
  - oraclejdk8
install: ./configure-build-node.sh
after_success:
  - mvn clean
  - export COMMIT_MESSAGE="$(git log -1 --oneline)"
  - echo $COMMIT_MESSAGE
  - test "${TRAVIS_BRANCH}" == "master" && test "${COMMIT_MESSAGE}" =~ "Make Release" && ./release.sh
#  - test "${TRAVIS_TAG}" != "" && ./release.sh
